package app.trustcam

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Vectors generated by spikes/pdq_ref.py on formula images
 * (checksum_vectors.json pdqCases). Hamming tolerance 2 covers float
 * rounding differences across platforms; expected distance is 0.
 */
class PdqTest {
    private class Case(
        val name: String, val width: Int, val height: Int,
        val bits: String, val luma: (Int, Int) -> Int
    )

    private val cases = listOf(
        Case("mix640x480", 640, 480,
            "0110110110010000011101001000111011110101111100110001001011101111001100000000010100110111100101011111101001100001001110111111000110111110111110100111110101000100011010101000010101111101100010011110000100001011010000101011100010000010000000001001101001111001"
        ) { x, y -> (x * 7 + y * 13 + (x * y) % 31) % 256 },
        Case("grad512x512", 512, 512,
            "1001101010001010010101010101110110101010101010100101010101010101101010101010101001010101010101011010101010101010010101010101010110101010101010100101010101010101101010101010101001010101010101011010101010101010010101010101010110101010101010100101010101010101"
        ) { x, y -> ((x * 255 / 511) + (y * 255 / 511)) / 2 },
        Case("blocks300x200", 300, 200,
            "0000000000011111111111111100000000000000000111111111111111000000000000000001111111111111110000000000000000011111000000000011111111111111111000001010101010110101111111111110000010101010101101011111111111100000010101010011010100101010111000001010101010110000"
        ) { x, y -> ((x / 25 + y / 25) % 2) * 200 + (x + y) % 55 }
    )

    @Test
    fun matchesReferenceHash() {
        for (c in cases) {
            val luma = FloatArray(c.width * c.height)
            for (y in 0 until c.height) {
                for (x in 0 until c.width) luma[y * c.width + x] = c.luma(x, y).toFloat()
            }
            val bits = Pdq.hash256(luma, c.width, c.height)
            val ham = bits.indices.count { bits[it] != c.bits[it] - '0' }
            assertTrue("${c.name}: hamming distance $ham > 2", ham <= 2)
        }
    }

    @Test
    fun hash104PacksFirstBitsMsbFirst() {
        for (c in cases) {
            val luma = FloatArray(c.width * c.height)
            for (y in 0 until c.height) {
                for (x in 0 until c.width) luma[y * c.width + x] = c.luma(x, y).toFloat()
            }
            val bits = Pdq.hash256(luma, c.width, c.height)
            val packed = Pdq.hash104(luma, c.width, c.height)
            assertEquals("${c.name}: size", 13, packed.size)
            for (k in 0 until 104) {
                val got = (packed[k / 8].toInt() shr (7 - k % 8)) and 1
                assertEquals("${c.name}: bit $k", bits[k], got)
            }
        }
    }
}
